server:
  port: 3344

spring:
    application:
      name: cloud-config-center
    cloud:
      config:
        server:
          git:
            uri: git@github.com:chenpx0128/SpringCloud-Config2020.git  #git仓库地址
          #####搜索目录
            search-paths:
              - SpringCloud-Config2020
        ##读取分支
        label: master


eureka:
  client:
    #表示自己注册进Eurekaserver
    registry-with-eureka: true
    #是否从eurekaserver中抓取已有的注册信息，默认true。单节点无所谓，集群必须设置true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

