server:
  port: 80

spring:
    application:
      name: cloud-feign




eureka:
  client:
    #表示自己注册进Eurekaserver
    registry-with-eureka: true
    #是否从eurekaserver中抓取已有的注册信息，默认true。单节点无所谓，集群必须设置true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#feign客户端超时的时间（openfeign默认支持ribbon）
ribbon:
  #读取服务端的资源所用的时间
  ReadTimeOut: 5000
  #建立连接所用的时间
  ConnectTime: 5000
logging:
  level:
    #feign是以什么级别监控日志，监控哪个接口
    springcloud.service.PaymentFeignService: debug
