server:
  port: 8001

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
    application:
      name: cloud-provider-hystrix-payment


eureka:
  client:
    #表示自己注册进Eurekaserver
    registry-with-eureka: true
    #是否从eurekaserver中抓取已有的注册信息，默认true。单节点无所谓，集群必须设置true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment-Hystrix8001
      #访问路径可以显示ip地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔（默认30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳等待的时间上限默认90秒
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: springcloud.entities #所有Entity别名类所在包
